### ISSUE TITLE
Add "Comradery" to List

### ISSUE THREAD

**Issue by Deer-Spangle** [Qwaxi-Lixard/no-porn-allowed#18]
**What company should be added?**
Comradery

**What service do they provide?**
Subscription Services

**What Document is the clause found in?**
https://comradery.co/p/tos

**What Section is it under?**
USER GENERATED CONTRIBUTIONS part 6

**Have any additional comments?**
It forbids obscene and lewd content, which sounds like it bans porn?
It only has 25 creators on it at the moment anyway though

**Comment by Qwaxi-Lixard** [comment]
Yeah, I would count that. They also use stripe as a payment processors which bans adult content from being funded through their service.

**Comment by Qwaxi-Lixard** [comment]
Finally added in https://github.com/Qwaxi-Lixard/no-porn-allowed/commit/64531a7e900b7e214c9ae212e0fc2196b0dd4ec4
