### ISSUE TITLE
Add "JotForm" to List

### ISSUE THREAD

**Issue by mruac** [Qwaxi-Lixard/no-porn-allowed#19]
**What company should be added?**
JotForm

**What service do they provide?**
Form and payment service

**What Document is the clause found in?**
[Terms of Use
](https://www.jotform.com/terms/#:~:text=You%20may%20not%20use%20the%20Service,to%20whether%20such%20content%20is%20present.)
**What Section is it under?**
**2. Limitations on Use of the Services**

**Have any additional comments?**
An artist used this service to provide a way to commission them.

**Comment by Qwaxi-Lixard** [comment]
Finally added in https://github.com/Qwaxi-Lixard/no-porn-allowed/commit/64531a7e900b7e214c9ae212e0fc2196b0dd4ec4
