### ISSUE TITLE
Add "Mollie" to List

### ISSUE THREAD

**Issue by joepie91** [Qwaxi-Lixard/no-porn-allowed#21]
**What company should be added?**

Mollie

**What service do they provide?**

Payment processing

**What Document is the clause found in?**

https://www.mollie.com/user-agreement

**What Section is it under?**

- SECTION 4: YOUR OBLIGATIONS
- Article 4.1.    Prohibited Activities
- "Activities for which Mollie cannot provide its services include, but are not limited to [...]: erotic content or services, [...]"

**Have any additional comments?**

Primarily used in NL, but also operates internationally.

**Comment by Qwaxi-Lixard** [comment]
Added to the list
